//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGNITE.Student
{
    public partial class Achievements
    {
        /// <summary>
        /// litUnlockedCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUnlockedCount;

        /// <summary>
        /// litTotalCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalCount;

        /// <summary>
        /// litRemainingCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRemainingCount;

        /// <summary>
        /// litProgressPercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProgressPercent;

        /// <summary>
        /// litBadgesUnlocked control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBadgesUnlocked;

        /// <summary>
        /// litTotalAchievementsXP control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalAchievementsXP;

        /// <summary>
        /// litStreakAchievementDays control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStreakAchievementDays;

        /// <summary>
        /// litQuestsFinished control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litQuestsFinished;
    }
}
