//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGNITE.Student
{
    public partial class StudentMaster
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        protected global::System.Web.UI.HtmlControls.HtmlAnchor navDashboard;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navHabits;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navTasks;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navGoals;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navChallenges;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navCalendar;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navProgress;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navSettings;

        protected global::System.Web.UI.WebControls.Literal litStudentName;
        protected global::System.Web.UI.WebControls.Literal litStudentLevelTitle;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder PageTitleContent;
        protected global::System.Web.UI.WebControls.Literal litStreakDays;
        protected global::System.Web.UI.WebControls.Literal litLevelNum;
        protected global::System.Web.UI.WebControls.Literal litXPText;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl xpProgressBar;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlNotifDot;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ScriptsContent;
    }
}
