//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGNITE.Student
{
    public partial class XP
    {
        /// <summary>
        /// litHeaderFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeaderFirstName;

        /// <summary>
        /// litHeroLevel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeroLevel;

        /// <summary>
        /// litHeroTotalXP control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeroTotalXP;

        /// <summary>
        /// litHeroStreakDays control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeroStreakDays;

        /// <summary>
        /// barHeroFill control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl barHeroFill;
    }
}
