//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGNITE.Admin
{
    public partial class AdminMaster
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        protected global::System.Web.UI.HtmlControls.HtmlAnchor navOverview;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navStudents;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navChallenges;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navQuests;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navAchievements;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navSettings;

        protected global::System.Web.UI.WebControls.Literal litAdminTitle;
        protected global::System.Web.UI.WebControls.LinkButton btnAdminLogout;

        protected global::System.Web.UI.WebControls.Literal litSystemStatus;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ScriptsContent;
    }
}
