//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGNITE.Admin
{
    public partial class Login
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlError;
        protected global::System.Web.UI.WebControls.Literal litErrorMessage;
        protected global::System.Web.UI.WebControls.TextBox txtAdminId;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAdminId;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
