//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGNITE.Admin
{
    public partial class Overview
    {
    }
}
